services:
  gateway:
    build: .
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-andrej_projekt_1}
      DB_USER: ${DB_USER:AJAMRICH
      DB_PASSWORD: ${DB_PASSWORD:Expedition78,}
      JWT_SECRET: ${JWT_SECRET:12345678901234567890123456789012}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-3600000}
    ports:
      - "8080:8080"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true